name: backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
        image:node:15-slim
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm ci
          npm test

